### PR TITLE
script to help sync between two dist-git repos

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by spetrosi** [comment]
Can you provide some more info on when to use this?

**Comment by spetrosi** [comment]
Do you run the script from a fedora or from centos repo? And how exactly do you run it? I'll use it for syncing ansible-collection-microsoft-sql too.

**Comment by richm** [comment]
> Do you run the script from a fedora or from centos repo? And how exactly do you run it? I'll use it for syncing ansible-collection-microsoft-sql too.

I have a local directory in which I work on rpm packaging for all of fedora, centos, and rhel.  I have git remotes for all of them.  It was originally cloned from fedora dist-git linux-system-roles, then I added remotes for centos and rhel.
```bash
> pwd
~/fedpkg/linux-system-roles
> git remote -v
cs      https://gitlab.com/redhat/centos-stream/rpms/rhel-system-roles.git (fetch)
cs      https://gitlab.com/redhat/centos-stream/rpms/rhel-system-roles.git (push)
cs-richm        git+ssh://git@gitlab.com/richm2/rhel-system-roles.git (fetch)
cs-richm        git+ssh://git@gitlab.com/richm2/rhel-system-roles.git (push)
origin  ssh://rmeggins@pkgs.fedoraproject.org/rpms/linux-system-roles (fetch)
origin  ssh://rmeggins@pkgs.fedoraproject.org/rpms/linux-system-roles (push)
rh      ssh://rmeggins@RH_DIST_GIT/rpms/rhel-system-roles (fetch)
rh      ssh://rmeggins@RH_DIST_GIT/rpms/rhel-system-roles (push)
rh-gl-richm     ssh://git@gitlab.com/richm2/rh-rhel-system-roles.git (fetch)
rh-gl-richm     ssh://git@gitlab.com/richm2/rh-rhel-system-roles.git (push)
rmeggins        ssh://rmeggins@pkgs.fedoraproject.org/forks/rmeggins/rpms/linux-system-roles.git (fetch)
rmeggins        ssh://rmeggins@pkgs.fedoraproject.org/forks/rmeggins/rpms/linux-system-roles.git (push)
```
The remote `cs` is centos and has the `c9s` branch.  This assumes you have already done the update in centos, and done a `git pull` so that your local cs/c9s branch is up-to-date.
so I run the script like this:
```bash
dry_run=false ~/linux-system-roles/auto-maintenance/sync-with-dist-git.sh -s c9s origin eln
```
Once this is done, you will be in the `eln` branch, and can do a `fedpkg build`.

**Review by spetrosi — APPROVED** [review]
Nice, it's a great idea to add those repos as git remotes

**Pull request merged**
