### PR TITLE
Add the initial collecion changelog file

### PR DESCRIPTION
**Pull request by nhosoi**
lsr_role2collection/COLLECTION_CHANGELOG.md

### CODE REVIEW

**Comment by richm** [comment]
hmm - it doesn't seem that readable to just put the role changelog contents in there, especially since we will have all of the roles changelogs in the collection.  How hard would it be to have a format like this:
```

[1.24.2] - 2022-06-15
---------------------

## New Features

- network - some new feature
- storage - some new feature

## Bug Fixes

- sshd - The role still supports 2.9
- kernel_settings - zzzz was broken - now it works
```
I would like to omit the `Other Changes` section - we should only have a collection release if there new features or bug fixes

Also, there are a large number of empty lines at the end of the file

**Comment by richm** [comment]
This looks nice!

**Comment by richm** [comment]
lgtm - ready to merge?

**Comment by richm** [comment]
you'll need to rebase to latest `master` branch

**Comment by nhosoi** [comment]
> you'll need to rebase to latest `master` branch

Thanks! Done.

**Review by richm — APPROVED** [review]
lgtm

**Pull request merged**
