### PR TITLE
release_collection.py - convert CHANGELOG.md into the reST format

### PR DESCRIPTION
**Pull request by nhosoi**
@spetrosi, @richm, could you please take a look? Thanks!

### CODE REVIEW

**Comment by nhosoi** [comment]
Although this is not directly related to this pr, there is one known issue in handling the main vs. master branch. It seems the `kernel_setting` switched from `master` to `main`, but `origin/HEAD` is still pointing to `origin/master` (not like `metrics` does to `origin/main`).
```
$ git branch -r
  origin/HEAD -> origin/master
  origin/main
  origin/master
```
It causes the `release_collection.py` running to fail for me. So, in my testing, I skipped `kernel_settings`.

**Comment by nhosoi** [comment]
https://github.com/linux-system-roles/auto-maintenance/pull/197 brought me this question...

Prior to running `release_collection.py`, the workflow script runs `pip install --upgrade pip` to ensure it has all the python modules updated, which is good.

Now, I'm adding these imports to this pr. Can I expect these modules are found in the pip list?
```
import pypandoc
from rst2html import rst2html
```

**Comment by nhosoi** [comment]
Another question - This pr converts CHANGELOG.md to CHANGELOG.rst and places it in the collection top directory (fedora/linux_system_roles). The original CHANGELOG.md is still in the collection docs directory. Do we want to remove it? Also, do we like to introduce an option to choose CHANGELOG.md or CHANGELOG.rst?

**Comment by richm** [comment]
> Another question - This pr converts CHANGELOG.md to CHANGELOG.rst and places it in the collection top directory (fedora/linux_system_roles). The original CHANGELOG.md is still in the collection docs directory. Do we want to remove it?

I think it is ok to leave it, but the discussion at https://src.fedoraproject.org/rpms/linux-system-roles/pull-request/84 may have some impact on what we do.  If it will complicate the spec file to have the docs/CHANGELOG.md, then let's omit it.

> Also, do we like to introduce an option to choose CHANGELOG.md or CHANGELOG.rst?

No, I think in this case it is ok to have it always produce .rst.

**Comment by richm** [comment]
> Although this is not directly related to this pr, there is one known issue in handling the main vs. master branch. It seems the `kernel_setting` switched from `master` to `main`, but `origin/HEAD` is still pointing to `origin/master` (not like `metrics` does to `origin/main`).
> 
> ```
> $ git branch -r
>   origin/HEAD -> origin/master
>   origin/main
>   origin/master
> ```
> 
> It causes the `release_collection.py` running to fail for me. So, in my testing, I skipped `kernel_settings`.

hmm 
```
git clone https://github.com/linux-system-roles/kernel_settings
cd kernel_settings
>git branch -a
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/lsr-template-sync
  remotes/origin/main
>git branch -r
  origin/HEAD -> origin/main
  origin/lsr-template-sync
  origin/main
```
Is this not what you see?

**Comment by nhosoi** [comment]
> > Although this is not directly related to this pr, there is one known issue in handling the main vs. master branch. It seems the `kernel_setting` switched from `master` to `main`, but `origin/HEAD` is still pointing to `origin/master` (not like `metrics` does to `origin/main`).
> > ```
> > $ git branch -r
> >   origin/HEAD -> origin/master
> >   origin/main
> >   origin/master
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It causes the `release_collection.py` running to fail for me. So, in my testing, I skipped `kernel_settings`.
> 
> hmm
> 
> ```
> git clone https://github.com/linux-system-roles/kernel_settings
> cd kernel_settings
> >git branch -a
> * main
>   remotes/origin/HEAD -> origin/main
>   remotes/origin/lsr-template-sync
>   remotes/origin/main
> >git branch -r
>   origin/HEAD -> origin/main
>   origin/lsr-template-sync
>   origin/main
> ```
> 
> Is this not what you see?

Ahhh, I should have removed the existing clone and cloned it again. Now I see it points to the `main` branch. Sorry for the noise.

**Review by richm — DISMISSED** [review]

**Comment by richm** [comment]
ready to merge?

**Comment by nhosoi** [comment]
> ready to merge?

Sorry, give me one sec... I may need to make one update...

**Comment by nhosoi** [comment]
> ready to merge?

Yes, I think so. Thanks for your patience. I found we needed to make sure the `write` was completed. :p
```
--- a/release_collection.py
+++ b/release_collection.py
@@ -639,6 +639,7 @@ def update_collection(args, galaxy, coll_rel):
                     "^Changelog\n=========\n", "", _clogs, flags=re.MULTILINE
                 )
                 clf.write(_clogs)
+            clf.flush()
             # Overwrite the original changelog with the new one.
             logging.info(
                 f"{orig_cl_file} is updated. Please merge to the master branch"
-- 
```

**Review by richm — APPROVED** [review]

**Pull request merged**
