### PR TITLE
lsr_role2collection.py Introducing --new-role

### PR DESCRIPTION
**Pull request by spetrosi**
mssql and some other roles need to change this:
    ```
      - name: Run the role with default parameters
        include_role:
        name: linux-system-roles.mssql
    ```
    to this:
    ```
      - name: Run the role with default parameters
        include_role:
        name: microsoft.sql.server
    ```
    python lsr_role2collection.py --role mssql --new-role server --namespace microsoft --collection sql

### CODE REVIEW

**Comment by nhosoi** [comment]
Looks good to me. May I ask you a couple of things?
1) Could you fix [the minor errors from black](https://github.com/linux-system-roles/auto-maintenance/pull/66/checks?check_run_id=2400403675)?
2) If you could also fix the issue https://github.com/linux-system-roles/auto-maintenance/issues/67 you figured, I'd appreciate it.
3) Could you add the option to the auto-maintenance README.md?

Thanks!

**Comment by spetrosi** [comment]
Hi Noriko,
> Looks good to me. May I ask you a couple of things?
> 
>     1. Could you fix [the minor errors from black](https://github.com/linux-system-roles/auto-maintenance/pull/66/checks?check_run_id=2400403675)?
Could you please give me a hint why black tests failed? I see an error message saying that the reformatted file has been reformatted, what is the issue with this?
> 
>     2. If you could also fix the issue #67 you figured, I'd appreciate it.
I'll try.
> 
>     3. Could you add the option to the auto-maintenance README.md?
Will do.

**Comment by nhosoi** [comment]
> Hi Noriko,
> 
> > Looks good to me. May I ask you a couple of things?
> > ```
> > 1. Could you fix [the minor errors from black](https://github.com/linux-system-roles/auto-maintenance/pull/66/checks?check_run_id=2400403675)?
> > ```
> 
> Could you please give me a hint why black tests failed? I see an error message saying that the reformatted file has been reformatted, what is the issue with this?

Well, all `black` cares is how the source code looks... There's no logical error nor actually anything wrong in your code. In this case, adding one argument `newrolename` made the line length limit exceed. And to fold the line, `black` recommends to put each argument in a line. We are supposed to do copy & paste. ;)

> > ```
> > 2. If you could also fix the issue #67 you figured, I'd appreciate it.
> > ```
> 
> I'll try.

Thanks!

> > ```
> > 3. Could you add the option to the auto-maintenance README.md?
> > ```
> 
> Will do.

Thanks, again!

**Comment by richm** [comment]
> And to fold the line, black recommends to put each argument in a line

you can use `black` to format the code for you.
```
. .tox/black/bin/activate
black lsr_role2collection.py
deactivate
```
then `tox -e black` should report success

**Review by nhosoi — DISMISSED** [review]
lgtm
Great job!
Please squash the 6 commits into one before the merge (Also, please do not forget to reset author with `git commit --amend --reset-author` if it's not automatically done.) Thanks!

**Comment by spetrosi** [comment]
I've squashed the commits as per Noriko's request, I indeed needed to reset the author, thank you @nhosoi for the instructions.

**Review by nhosoi — APPROVED** [review]
lgtm

**Review by richm — APPROVED** [review]
lgtm

**Pull request merged**
