### PR TITLE
add support for tox with pylint, pyunit, flake8, black, shellcheck

### PR DESCRIPTION
**Pull request by richm**
add support for tox with pylint, pyunit, flake8, black, shellcheck

### CODE REVIEW

**Comment by richm** [comment]
@nhosoi this will give you the ability to do linting/formatting of your python file, and the ability to do unit testing of your functions e.g. you could create a unit test like `tests/unit/test_lsr_role2collection.py` like this:
```python
# SPDX-License-Identifier: GPL-2.0-or-later
"""unit tests for lsr_role2collection"""

import unittest

import lsr_role2collection

class LSRRole2Collection(unittest.TestCase):
    """test lsr_role2collection"""

    def test_add_rolename(self):
        """test add_rolename"""
        result = lsr_role2collection.add_rolename("README.md", "rolename")
        self.assertEqual("README-rolename.md", result)
        ... more tests for this ...

    def test_for_other_funcs(self):
        """tests for other funcs""""
....
```

**Comment by richm** [comment]
@nhosoi note that if you use this, you will have to rename the python script to be lsr_role2collection.py

**Comment by nhosoi** [comment]
Thank you, @richm!!
I checked out this pr and ran pylint, black, etc. against my local changes (and I got lots of errors/warnings :) which make sense.
One error not clear to me is from `tox -e shellcheck`. Is the command line wrong to start shellcheck?
```
shellcheck create: /home/nhosoi/linux-system-roles/auto-maintenance/.tox/shellcheck
shellcheck run-test-pre: PYTHONHASHSEED='1524971774'
shellcheck run-test: commands[0] | bash -c 'shellcheck -e SC1090 *.sh'
/usr/bin/bash: shellcheck: command not found
ERROR: InvocationError for command /usr/bin/bash -c 'shellcheck -e SC1090 *.sh' (exited with code 127)
___________________________________ summary ____________________________________
ERROR:   shellcheck: commands failed
```

**Comment by richm** [comment]
> Thank you, @richm!!
> I checked out this pr and ran pylint, black, etc. against my local changes (and I got lots of errors/warnings :) which make sense.
> One error not clear to me is from `tox -e shellcheck`. Is the command line wrong to start shellcheck?

You have to install shellcheck manually since it isn't a python pypi package: `dnf -y install shellcheck`

> 
> ```
> shellcheck create: /home/nhosoi/linux-system-roles/auto-maintenance/.tox/shellcheck
> shellcheck run-test-pre: PYTHONHASHSEED='1524971774'
> shellcheck run-test: commands[0] | bash -c 'shellcheck -e SC1090 *.sh'
> /usr/bin/bash: shellcheck: command not found
> ERROR: InvocationError for command /usr/bin/bash -c 'shellcheck -e SC1090 *.sh' (exited with code 127)
> ___________________________________ summary ____________________________________
> ERROR:   shellcheck: commands failed
> ```

**Comment by nhosoi** [comment]
Nice. Thanks! (did you know dnf is case sensitive? Even worse, `dnf search shellcheck` does **not** return `ShellCheck` but just `ghc-ShellCheck` and its friends... Very confusing...):
```
$ tox -e shellcheck
shellcheck run-test-pre: PYTHONHASHSEED='2970326927'
shellcheck run-test: commands[0] | bash -c 'shellcheck -e SC1090 *.sh'
____________________________________________________ summary ____________________________________________________
  shellcheck: commands succeeded
  congratulations :)
```

**Comment by richm** [comment]
> Nice. Thanks! (did you know dnf is case sensitive? Even worse, `dnf search shellcheck` does **not** return `ShellCheck` but just `ghc-ShellCheck` and its friends... Very confusing...):

added a check for shellcheck - if it is not in your PATH, you will get an error message like this:
`ERROR: shellcheck not found - try dnf -y install ShellCheck`

**Comment by richm** [comment]
@nhosoi is this latest commit working for you?

**Comment by nhosoi** [comment]
> @nhosoi is this latest commit working for you?

I ran lsr-roles2collections.sh, which converts "certificate kdump kernel_settings logging metrics nbde_client nbde_server network selinux storage timesync tlog tuned" and I did not see any errors... I quickly run one tests tests_sanity_fullstack.yml from metrics, which successfully done.

Could you please give me some more details like which role is not working and errors you got? Thanks!

**Comment by nhosoi** [comment]
> @nhosoi is this latest commit working for you?

Yes, it is. My approval is for the latest commit you mentioned. Please merge this pr.
(And sorry for my comment I mistakenly put, which removed it....:p)

**Pull request merged**
