### PR TITLE
lsr_role2collection.py - copy each role's README.md and CHANGELOG.md

### PR DESCRIPTION
**Pull request by nhosoi**
Copy each role's `README.md` and `CHANGELOG.md` to the collections doc dir with renamed filename `README_ROLENAME.md` and `CHANGELOG_ROLENAME.md`, respectively.

### CODE REVIEW

**Review by richm — DISMISSED** [review]
lgtm

**Review by spetrosi — APPROVED** [review]

**Comment by nhosoi** [comment]
Thank you for your reviews, @richm, @spetrosi.
Rebased and merged.

**Comment by spetrosi** [comment]
tox `collection` test fails on https://github.com/linux-system-roles/mssql/pull/77 with
`FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/mssql/mssql/.tox/ansible_collections/fedora/linux_system_roles/docs/README_mssql.md'`
@nhosoi do you know how to fix this?

**Comment by nhosoi** [comment]
> tox `collection` test fails on [linux-system-roles/mssql#77](https://github.com/linux-system-roles/mssql/pull/77) with `FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/mssql/mssql/.tox/ansible_collections/fedora/linux_system_roles/docs/README_mssql.md'` @nhosoi do you know how to fix this?

Ahhh, sorry, @spetrosi. I should have checked the `docs` dir existed before copying the files. Opening a pr to fix it.
```
ansible_collections/fedora/linux_system_roles/docs/
```

**Comment by nhosoi** [comment]
@spetrosi, I've opened a pr to fix the issue: https://github.com/linux-system-roles/auto-maintenance/pull/170

**Pull request merged**
