### PR TITLE
RHELPLAN-59755 - Collection - script - not include symlinks in the collection converted format

### PR DESCRIPTION
**Pull request by nhosoi**
Fixing a copying symlink bug.
Function lsr_copytree should keep symlinks if option symlinks is True;
copy its contents if option symlinks is False. There was a bug to check
symlink in lsr_copytree. Path.is_dir returns true for symlink dir and
it's treated as a directory.

### CODE REVIEW

**Comment by richm** [comment]
There is one place where we want to preserve symlinks.  In the `vars/` directory, it is quite common to have something like this:
```
vars/
  RedHat-8.yml
  CentOS-8.yml -> RedHat-8.yml
```
That is - the role needs to set specific variables for rhel8 or centos8 - but rather than have two separate files that are otherwise identical, the role will use RedHat-8.yml as the "real" file, and CentOS-8.yml is just a link to RedHat-8.yml

**Comment by nhosoi** [comment]
> There is one place where we want to preserve symlinks. In the `vars/` directory, it is quite common to have something like this:
> 
> ```
> vars/
>   RedHat-8.yml
>   CentOS-8.yml -> RedHat-8.yml
> ```
> 
> That is - the role needs to set specific variables for rhel8 or centos8 - but rather than have two separate files that are otherwise identical, the role will use RedHat-8.yml as the "real" file, and CentOS-8.yml is just a link to RedHat-8.yml

Right. I have no plan to touch the symlinks under the `roles` dir. It is for the `tests` dir. And this change is rather for fixing a bug in the previous commit 9cf9aaeb49e72f5096e79a0f5866a2a178b9b18c...

**Review by richm — APPROVED** [review]
lgtm

**Comment by nhosoi** [comment]
Thanks for your reviewing this pr, @richm.

**Pull request merged**
