### PR TITLE
[WIP] Improve update_vendored_collections.py and prepare to run in container

### PR DESCRIPTION
**Pull request by spetrosi**
Please review for Python best practices

### CODE REVIEW

**Comment by spetrosi** [comment]
Note to self: At the end of the script, update [auto-maintenance/vendored_collections.yml](https://github.com/linux-system-roles/auto-maintenance/blob/master/update_vendored_collections/vendored_collections.yml) with new current versions and push here to open a PR

**Review by richm — APPROVED** [review]
lgtm

**Comment by richm** [comment]
I don't think the collection tarballs should be committed to git

**Comment by spetrosi** [comment]
> I don't think the collection tarballs should be committed to git

You are right, we cannot publicly share AH tarballs. Thank you for the input, removed

**Review by richm — DISMISSED** [review]
lgtm
probably the version of black changed recently - we should fix that in a separate commit

**Review by richm — APPROVED** [review]
lgtm

**Pull request merged**
