### PR TITLE
remove dependency on ansible, use only ruamel parser

### PR DESCRIPTION
**Pull request by richm**
We only were using the Ansible parser to extract the task module
name and arguments.  We don't need this full parsing.  We only
need to look for a few module names, such as ones related to
roles, and ones related to role modules.  This is quite easily
done without the Ansible parser.

### CODE REVIEW

**Review by nhosoi — DISMISSED** [review]
Looks great!!
I reviewed the pr and ran the CI tests.

**Comment by richm** [comment]
> Looks great!!
> I reviewed the pr and ran the CI tests.

@pcahyna what say you?

**Comment by pcahyna** [comment]
looks good - and it does not even seem to be a very invasive change, I was afraid that the Ansible parser was ingrained more deeply in the tool.

**Comment by pcahyna** [comment]
I compared the resulting builds made by this version and the previous version. The builds are exactly identical.

**Review by pcahyna — DISMISSED** [review]

**Comment by richm** [comment]
rebased - please review/approve again

**Comment by richm** [comment]
ready to merge?

**Review by nhosoi — APPROVED** [review]
lgtm

**Comment by nhosoi** [comment]
> ready to merge?

Yes, please!

**Pull request merged**
